/*
 * This file is generated by jOOQ.
 */
package uk.co.mr.finance.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import uk.co.mr.finance.db.tables.JDatabasechangelog;
import uk.co.mr.finance.db.tables.JDatabasechangeloglock;
import uk.co.mr.finance.db.tables.JLoadControl;
import uk.co.mr.finance.db.tables.JStatementData;
import uk.co.mr.finance.db.tables.JTransactionType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPublic extends SchemaImpl {

    private static final long serialVersionUID = -11035402;

    /**
     * The reference instance of <code>public</code>
     */
    public static final JPublic PUBLIC = new JPublic();

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final JDatabasechangelog DATABASECHANGELOG = JDatabasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final JDatabasechangeloglock DATABASECHANGELOGLOCK = JDatabasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.load_control</code>.
     */
    public final JLoadControl LOAD_CONTROL = JLoadControl.LOAD_CONTROL;

    /**
     * The table <code>public.statement_data</code>.
     */
    public final JStatementData STATEMENT_DATA = JStatementData.STATEMENT_DATA;

    /**
     * The table <code>public.transaction_type</code>.
     */
    public final JTransactionType TRANSACTION_TYPE = JTransactionType.TRANSACTION_TYPE;

    /**
     * No further instances allowed
     */
    private JPublic() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            JDatabasechangelog.DATABASECHANGELOG,
            JDatabasechangeloglock.DATABASECHANGELOGLOCK,
            JLoadControl.LOAD_CONTROL,
            JStatementData.STATEMENT_DATA,
            JTransactionType.TRANSACTION_TYPE);
    }
}
