/*
 * This file is generated by jOOQ.
 */
package uk.co.mr.finance.db;


import uk.co.mr.finance.db.tables.JDatabasechangelog;
import uk.co.mr.finance.db.tables.JDatabasechangeloglock;
import uk.co.mr.finance.db.tables.JLoadControl;
import uk.co.mr.finance.db.tables.JStatementData;
import uk.co.mr.finance.db.tables.JTransactionType;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final JDatabasechangelog DATABASECHANGELOG = JDatabasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final JDatabasechangeloglock DATABASECHANGELOGLOCK = JDatabasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.load_control</code>.
     */
    public static final JLoadControl LOAD_CONTROL = JLoadControl.LOAD_CONTROL;

    /**
     * The table <code>public.statement_data</code>.
     */
    public static final JStatementData STATEMENT_DATA = JStatementData.STATEMENT_DATA;

    /**
     * The table <code>public.transaction_type</code>.
     */
    public static final JTransactionType TRANSACTION_TYPE = JTransactionType.TRANSACTION_TYPE;
}
